package at.eliastrummer.util;

public class HTMLTemplate {

    public static final String TEMPLATE = "<html>\n"
            + "  <head>\n"
            + "\n"
            + "  </head>\n"
            + "  <body>\n"
            + "   <h1 style=\"color: blue; text-align:center;\">{TITLE}</h1>\n"
            + "   <h2 style=\"color: #333; text-align:center; text-decoration:underline;\">{AUTHOR}</h2>\n"
            + "   <hr style=\"color:black;\"/>\n"
            + "   <div style=\"text-align:center; margin: 0 auto;\">\n"
            + "      <span style=\"color: green; text-align:left\">ISBN:</span>\n"
            + "      <span style=\"text-align:left;\">{ISBN}</span>\n"
            + "    </div>\n"
            + "   <div style=\"text-align:center; margin: 0 auto;\">\n"
            + "      <span style=\"color: green;  text-align:left\">Seitenzahl:</span>\n"
            + "      <span style=\"text-align:left;\">{PAGES}</span>\n"
            + "    </div>\n"
            + "   <div style=\"text-align:center; margin: 0 auto;\">\n"
            + "      <span style=\"color: green;  text-align:left\">Genre:</span>\n"
            + "      <span style=\"text-align:left;\">{GENRE}</span>\n"
            + "    </div>\n"
            + "   <div style=\"text-align:center; margin: 0 auto;\">\n"
            + "      <span style=\"color: green;  text-align:left\">Bewertungen:</span>\n"
            + "      <span style=\"text-align:left;\">{RATING}</span>\n"
            + "    </div>\n"
            + "   <div style=\"text-align:center; margin: 0 auto;\">\n"
            + "      <span style=\"color: green;  text-align:left\">Erscheinungsdatum:</span>\n"
            + "      <span style=\"text-align:left;\">{PUBLISHED_ON}</span>\n"
            + "    </div>\n"
            + "   <div style=\"text-align:center; margin: 0 auto;\">\n"
            + "      <span style=\"color: green;  text-align:left\">Verlag:</span>\n"
            + "      <span style=\"text-align:left;\">{PUBLISHER}</span>\n"
            + "    </div>\n"
            + "  </body>\n"
            + "</html>\n";
}
