/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package at.eliastrummer.kontoverwaltung.gui;

import at.eliastrummer.kontoverwaltung.bl.Account;
import at.eliastrummer.kontoverwaltung.bl.AccountUser;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author elias
 */
public class AccountGUI extends javax.swing.JFrame {
    
    private UserListModel userModel = new UserListModel();
    private List<Thread> threads = new ArrayList<>();
    private Account account = null;
    
    public AccountGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.ltUsers.setModel(userModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pomUsers = new javax.swing.JPopupMenu();
        miAddUser = new javax.swing.JMenuItem();
        miPerformAccountTest = new javax.swing.JMenuItem();
        pomCreateAccount = new javax.swing.JPopupMenu();
        miCreateAccount = new javax.swing.JMenuItem();
        lbBalance = new javax.swing.JLabel();
        pnContainer = new javax.swing.JSplitPane();
        spUsers = new javax.swing.JScrollPane();
        ltUsers = new javax.swing.JList<>();
        spAccountOutput = new javax.swing.JScrollPane();
        taOutput = new javax.swing.JTextArea();

        miAddUser.setText("Add User");
        miAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddUserActionPerformed(evt);
            }
        });
        pomUsers.add(miAddUser);

        miPerformAccountTest.setText("Perform Account Test");
        miPerformAccountTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPerformAccountTestActionPerformed(evt);
            }
        });
        pomUsers.add(miPerformAccountTest);

        miCreateAccount.setText("Create Account");
        miCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCreateAccountActionPerformed(evt);
            }
        });
        pomCreateAccount.add(miCreateAccount);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 450));

        lbBalance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbBalance.setText("648,00 €");
        lbBalance.setBorder(javax.swing.BorderFactory.createTitledBorder("Account Balance"));
        getContentPane().add(lbBalance, java.awt.BorderLayout.PAGE_END);

        pnContainer.setDividerLocation(160);

        spUsers.setBorder(javax.swing.BorderFactory.createTitledBorder("Users"));
        spUsers.setPreferredSize(new java.awt.Dimension(180, 180));

        ltUsers.setComponentPopupMenu(pomUsers);
        ltUsers.setMaximumSize(new java.awt.Dimension(50, 50));
        ltUsers.setPreferredSize(new java.awt.Dimension(40, 40));
        spUsers.setViewportView(ltUsers);

        pnContainer.setLeftComponent(spUsers);

        spAccountOutput.setBorder(javax.swing.BorderFactory.createTitledBorder("Account-Output"));

        taOutput.setEditable(false);
        taOutput.setColumns(20);
        taOutput.setRows(5);
        taOutput.setComponentPopupMenu(pomCreateAccount);
        spAccountOutput.setViewportView(taOutput);

        pnContainer.setRightComponent(spAccountOutput);

        getContentPane().add(pnContainer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddUserActionPerformed
        String result = JOptionPane.showInputDialog("Add user | Enter username");
        if(result.isEmpty()){
            return;
        }
        AccountUser user = new AccountUser(result, account, taOutput);
        if(userModel.exists(user)){
            return;
        }
        userModel.add(user);
    }//GEN-LAST:event_miAddUserActionPerformed

    private void miCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCreateAccountActionPerformed
        this.account = new Account(50, lbBalance, taOutput);
    }//GEN-LAST:event_miCreateAccountActionPerformed

    private void miPerformAccountTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPerformAccountTestActionPerformed
        if(account == null){
            miCreateAccountActionPerformed(null);
        }
        taOutput.setText("");
        threads.clear();
        List<AccountUser> selectedUsers = ltUsers.getSelectedValuesList();
        selectedUsers.forEach(user -> {
            user.setAccount(account);
            
            Thread t = new Thread(user, user.getName());
            t.setPriority(Thread.NORM_PRIORITY + 1);
            threads.add(t);
            t.start();
        });
    }//GEN-LAST:event_miPerformAccountTestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbBalance;
    private javax.swing.JList<AccountUser> ltUsers;
    private javax.swing.JMenuItem miAddUser;
    private javax.swing.JMenuItem miCreateAccount;
    private javax.swing.JMenuItem miPerformAccountTest;
    private javax.swing.JSplitPane pnContainer;
    private javax.swing.JPopupMenu pomCreateAccount;
    private javax.swing.JPopupMenu pomUsers;
    private javax.swing.JScrollPane spAccountOutput;
    private javax.swing.JScrollPane spUsers;
    private javax.swing.JTextArea taOutput;
    // End of variables declaration//GEN-END:variables
}
