/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package at.eliastrummer.bruteforce;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Elias
 */
public class BrutoForceGUI extends javax.swing.JFrame {

    /**
     * Creates new form BrutoForceGUI
     */
    
    private BrutoForceManager bfLauncher;
    private boolean isRunning = false;
    
    public BrutoForceGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnLeft = new javax.swing.JPanel();
        pnThreads = new javax.swing.JPanel();
        slAmountThreads = new javax.swing.JSlider();
        tfAmountThreads = new javax.swing.JTextField();
        tfAmountPasswords = new javax.swing.JTextField();
        btStarStop = new javax.swing.JButton();
        pnRight = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taLogger = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        pnLeft.setLayout(new java.awt.GridLayout(3, 1));

        pnThreads.setLayout(new java.awt.BorderLayout());

        slAmountThreads.setMaximum(10);
        slAmountThreads.setMinimum(1);
        slAmountThreads.setPaintLabels(true);
        slAmountThreads.setPaintTicks(true);
        slAmountThreads.setSnapToTicks(true);
        slAmountThreads.setValue(4);
        slAmountThreads.setBorder(javax.swing.BorderFactory.createTitledBorder("Anzahl an Threads"));
        slAmountThreads.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slAmountThreadsStateChanged(evt);
            }
        });
        pnThreads.add(slAmountThreads, java.awt.BorderLayout.CENTER);

        tfAmountThreads.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfAmountThreads.setText("4");
        tfAmountThreads.setPreferredSize(new java.awt.Dimension(50, 24));
        pnThreads.add(tfAmountThreads, java.awt.BorderLayout.LINE_END);

        pnLeft.add(pnThreads);

        tfAmountPasswords.setText("ALL");
        tfAmountPasswords.setBorder(javax.swing.BorderFactory.createTitledBorder("Anzahl an zu lösenden Passwörtern"));
        tfAmountPasswords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAmountPasswordsActionPerformed(evt);
            }
        });
        pnLeft.add(tfAmountPasswords);

        btStarStop.setText("START");
        btStarStop.setBorder(javax.swing.BorderFactory.createTitledBorder("Start / Stop Threads"));
        btStarStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStarStopActionPerformed(evt);
            }
        });
        pnLeft.add(btStarStop);

        getContentPane().add(pnLeft);

        pnRight.setBorder(javax.swing.BorderFactory.createTitledBorder("Logger"));
        pnRight.setEnabled(false);
        pnRight.setLayout(new java.awt.BorderLayout());

        taLogger.setColumns(20);
        taLogger.setRows(5);
        jScrollPane1.setViewportView(taLogger);

        pnRight.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnRight);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfAmountPasswordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAmountPasswordsActionPerformed
        
    }//GEN-LAST:event_tfAmountPasswordsActionPerformed

    private void btStarStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStarStopActionPerformed
        if(!isRunning){
            //START
            BrutoForceGUI _this = this;
            new Thread(new Runnable() {
                @Override
                public void run() {
                    int amountThreads = slAmountThreads.getValue();
                    String amountPasswords = tfAmountPasswords.getText();
                    int amountPasswordsToSolve = 0;

                    if(amountPasswords.equalsIgnoreCase("all")){
                        amountPasswordsToSolve = Integer.MAX_VALUE;
                    }else{
                        try{
                            amountPasswordsToSolve = Integer.parseInt(amountPasswords);
                        }catch(Exception e){
                            JOptionPane.showMessageDialog(_this, "Der Wert in 'Anzahl an zu lösenden Passwörtern' ist falsch! Gültig: \"ALL\" oder eine Zahl");
                            return;
                        }
                    }

                    bfLauncher = new BrutoForceManager(taLogger, amountThreads, amountPasswordsToSolve);
                    try {
                        isRunning = true;
                        btStarStop.setText("STOP");
                        bfLauncher.crackPasswords();
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(_this, "Es ist ein Fehler aufgetreten: " + ex.toString());
                        System.out.println(ex.toString());
                        isRunning = false;
                        btStarStop.setText("START");
                    }
                }
            }).start();
        }else{
            //STOP
            //System.out.println(isRunning);
            if(this.bfLauncher != null){
                System.out.println("here");
                this.bfLauncher.stop();
                isRunning = false;
                this.bfLauncher = null;
                this.btStarStop.setText("START");
            }
        }
    }//GEN-LAST:event_btStarStopActionPerformed

    private void slAmountThreadsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slAmountThreadsStateChanged
        this.tfAmountThreads.setText(Integer.toString(slAmountThreads.getValue()));
    }//GEN-LAST:event_slAmountThreadsStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrutoForceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrutoForceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrutoForceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrutoForceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrutoForceGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btStarStop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnRight;
    private javax.swing.JPanel pnThreads;
    private javax.swing.JSlider slAmountThreads;
    private javax.swing.JTextArea taLogger;
    private javax.swing.JTextField tfAmountPasswords;
    private javax.swing.JTextField tfAmountThreads;
    // End of variables declaration//GEN-END:variables
}
